apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-dashboard.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "go-dashboard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-dashboard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-dashboard.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "go-dashboard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONNECT_STRING_WSPUBSUB
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: CONNECT_STRING_WSPUBSUB
            - name: CONNECT_STRING_DOCUMENTDB
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: CONNECT_STRING_DOCUMENTDB
            - name: DOCUMENTDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: DOCUMENTDB_DATABASE
            - name: OBSERVER_URL
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: OBSERVER_URL
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
